/**
 * The read-out's second affordance (2026-07-21 simplification proposal, D5
 * "run findings become work"): "this run surfaced work -> open a todo."
 * Pure builder for the `todo.opened` payload the RunDetailModal's small
 * form POSTs -- kept out of the component so the payload shape (origin
 * stamp, bundle default, detail lines) is unit-testable like `todoQueue.ts`.
 *
 * Verdict and disposition stay orthogonal by construction: nothing here
 * reads, requires, or implies a grade -- the payload is buildable for an
 * ungraded, failed, or pass-graded run alike.
 */
import type { RunDetailRun, TodoKind, TodoStatus } from "./schemas.ts";

export interface RunTodoDraft {
  readonly run: RunDetailRun;
  /** The form's title field; a blank title builds nothing. */
  readonly title: string;
  /** The form's optional note; blank = omitted, the evidence line stands alone. */
  readonly note: string;
  /** `td-<uuid>`, generated by the caller so the builder stays pure. */
  readonly id: string;
  /** YYYY-MM-DD, generated by the caller so the builder stays pure. */
  readonly created: string;
}

export interface RunTodoPayload {
  readonly todo: {
    readonly id: string;
    readonly kind: TodoKind;
    readonly status: TodoStatus;
    readonly title: string;
    readonly detail: string;
    readonly priority: number;
    readonly bundle: string;
    readonly created: string;
    readonly source: { readonly kind: "user"; readonly name: string };
    readonly origin: { readonly kind: "run"; readonly runId: string };
  };
}

/**
 * `detail` always ends with the evidence line naming the run (and its
 * fixture case, when it has one) -- the origin chip links back, but the
 * detail text must stay honest even copied off-surface. The note, when
 * given, comes first: prose before provenance, same order as a
 * field-report-seeded todo's detail.
 */
export const buildRunTodoPayload = (draft: RunTodoDraft): RunTodoPayload | undefined => {
  const title = draft.title.trim();
  if (title.length === 0) {
    return undefined;
  }
  const note = draft.note.trim();
  const evidence = `Surfaced by run ${draft.run.id}${
    draft.run.fixtureCase !== undefined ? ` (fixture ${draft.run.fixtureCase})` : ""
  }.`;
  return {
    todo: {
      id: draft.id,
      // "task" mirrors the CLI door's default: a finding carries no
      // worked/failed/surprise outcome to key a kind off of.
      kind: "task",
      status: "open",
      title,
      detail: note.length > 0 ? `${note}\n${evidence}` : evidence,
      // DEFAULT_PRIORITY_BY_KIND.task (data-model.md §2.10).
      priority: 30,
      bundle: draft.run.bundle,
      created: draft.created,
      source: { kind: "user", name: "viewer" },
      origin: { kind: "run", runId: draft.run.id },
    },
  };
};
